spring.application.name=TaskManagementWithDbPersistence

#MSSQL Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=JPATrainingDB;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourPassword123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Spring JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Spring Dev Tool
spring.devtools.livereload.enabled=true

# Disable template cache during development (re-enable in production)
spring.thymeleaf.cache=false
# Template encoding
spring.thymeleaf.encoding=UTF-8
# Prefix and suffix (these are the defaults ? shown for clarity)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html 